git add arch/arm/include/asm/trustfull/hypercalls.h
git add arch/arm/include/asm/uaccess-asm.h
git add arch/arm/kernel/Makefile
git add arch/arm/lib/csumpartialcopyuser.S
git add arch/arm/mach-omap2/io.c
git add arch/arm/mm/cache-v7.S
git add arch/arm/mm/pgd.c
git add arch/arm/tools/syscall.tbl
git add drivers/bus/ti-sysc.c
git add drivers/dma/of-dma.c
git add drivers/dma/ti/cppi41.c
git add drivers/irqchip/irq-omap-intc.c
git add drivers/net/ethernet/ti/cpsw_new.c
git add drivers/usb/dwc3/dwc3-omap.c
git add drivers/usb/musb/am35x.c
git add drivers/usb/musb/da8xx.c
git add drivers/usb/musb/davinci.c
git add drivers/usb/musb/musb_core.c
git add drivers/usb/musb/musb_core.h
git add drivers/usb/musb/musb_cppi41.c
git add drivers/usb/musb/musb_dma.h
git add drivers/usb/musb/musb_dsps.c
git add drivers/usb/musb/musb_gadget.c
git add drivers/usb/musb/musb_host.c
git add drivers/usb/musb/musb_host.h
git add drivers/usb/musb/musb_virthub.c
git add drivers/usb/musb/omap2430.c
git add drivers/usb/phy/phy-am335x-control.c
git add drivers/usb/phy/phy-am335x.c
git add drivers/usb/phy/phy-generic.c
git add fs/binfmt_elf.c
git add fs/exec.c
git add include/linux/mm.h
git add include/linux/syscalls.h
git add include/uapi/asm-generic/unistd.h
git add kernel/fork.c
git add kernel/printk/printk.c
git add kernel/workqueue.c
git add mm/memory.c
git add mm/mmap.c
git add mm/util.c
